config/routes.rb
Top5::Application.routes.draw do
  get "tag/show"
  devise_for :users
  resources :lists do
  	member do
  		put "like", to: "lists#upvote"
  	end
  	get :autocomplete_tag_name, :on => :collection    
  end

  resources :tag

  root "lists#index"  

end

app/models/list.rb
class List < ActiveRecord::Base
	acts_as_votable
	belongs_to :user
	acts_as_taggable # Alias for acts_as_taggable_on :tags
	acts_as_taggable_on :tags


	has_attached_file :image, styles: { medium: "300x300>" }
	validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

	has_many :list_items, :dependent => :destroy
	accepts_nested_attributes_for 	:list_items,
									reject_if: lambda { |a| a[:title].blank? },
									allow_destroy: true
						
	validates :title, :description, presence: true

end

app/models/list_item.rb
class ListItem < ActiveRecord::Base
	belongs_to :list
end

app/models/tag.rb
class Tag < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  has_many :lists	   

  validates :username,
  :uniqueness => {
    :case_sensitive => false
  }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
	before_action :find_list, only: [:show, :edit, :update, :destroy, :upvote]
	before_action :authenticate_user!,except: [:index, :show]
	autocomplete :tag, :name, :class_name => 'ActsAsTaggableOn::Tag'

	def index
		@lists = List.all.order("created_at DESC")
	end

	def show
	end

	def new
		@list = current_user.lists.build
		5.times { @list.list_items.build } 
	end

	def create 
		@list = current_user.lists.build(list_params)

		if @list.save
			redirect_to @list, notice: "Successfully created new List"
		else
			render 'new'
		end
	end

	def edit
	end

	def update
		if @list.update(list_params)
			redirect_to @list, notice: "List was successfully updated!"
		else
			render 'edit'
		end
	end

	def destroy
		@list.destroy
		redirect_to root_path
	end

	def upvote
		@list.upvote_by current_user
		redirect_to :back
	end

	def tagged
	  if params[:tag].present? 
	    @lists = List.tagged_with(params[:tag])
	  else 
	    @lists = List.postall
	  end  
	end

	private

	def list_params
		params.require(:list).permit(
									:image, :title, :description, :tag_list,
									list_items_attributes: [:id, :ranking, :title, :url, :description, :_destroy])
	end 

	def find_list
		@list = List.find(params[:id])
	end


end

app/controllers/tag_controller.rb
class TagController < ApplicationController
	def show
		@tag = Tag.find params[:id]
		@lists = List.tagged_with(@tag.name)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def full_title(page_title)
		base_title = "Top5"
		page_title.empty? ?  base_title : "#{page_title} | #{base_title}"
 	end

end

app/helpers/lists_helper.rb
module ListsHelper
	include ActsAsTaggableOn::TagsHelper
end

app/helpers/tag_helper.rb
module TagHelper
end

app/views/layouts/application.html.haml
!!! 5
%html
%head
	%title= full_title(content_for :title)
	= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true	
	= javascript_include_tag "application", "data-turbolinks-track" => true, :cache => true
	= stylesheet_link_tag "application", "custom-theme/jquery-ui-1.8.9.custom" 
	= javascript_include_tag :defaults, "jquery-ui-#.#.#.custom.min", "autocomplete-rails"
	= csrf_meta_tags
%body
	%nav.navbar.navbar-default
		.container
			.navbar-brand= link_to "Top 5", root_path

			- if user_signed_in?
				%ul.nav.navbar-nav.navbar-right
					%li= link_to "New List", new_list_path
					%li= link_to "Account", edit_user_registration_path
					%li= link_to "Sign Out", destroy_user_session_path, method: :delete
			-else
				%ul.nav.navbar-nav.navbar-right	
					%li= link_to "Sign Up", new_user_registration_path
					%li= link_to "Sign In", new_user_session_path
	.container
		- flash.each do |name, msg|
			= content_tag :div, msg, class: "altert alert-info"
		= yield

app/views/lists/_form.html.haml
= simple_form_for @list, html: { multipart: true } do |f|
  - if @list.errors.any?
    #errors
      %h2
        = pluralize(@list.errors.count, "error")
        prevented this List from saving
      %ul
        - @list.errors.full_messages.each do |msg|
          %li= msg

  .form-group
    = f.label :tag_list, "Título da Lista"

  .form-group
    = f.autocomplete_field :tag_list, autocomplete_tag_name_lists_path, :"data-delimiter" => ', '
    / note tag_list above is a virtual column created by acts_as_taggable_on

  .form-group
    = f.input :image, input_html: { class: 'form-control' }

  .form-group
    = f.input :description, input_html: { class: 'form-control' }

  %h3 List Items
  #listitems
  = f.simple_fields_for :list_items do |builder|
    .p.fields
      = builder.input :title, input_html: { class: 'form-control' }
    %br/
  = f.button :submit, class: "btn btn-primary"

app/views/lists/edit.html.haml
- content_for :title, "Editar Lista"
.col-md-6.col-md-offset-3
	.row
		.panel.panel-default
			.panel-heading
				%h1 Edit List
			.panel-body
				%strong.center Current Image
				%br/
				= image_tag @list.image.url(:medium)			
				= render 'form'
				%br/
				= link_to "Cancel", list_path

app/views/lists/index.html.haml
- content_for :title, "Home"
#lists.transitions-enabled
	- @lists.each do |list|
		.box.panel.panel-default
			- if list.image.present?
				= link_to (image_tag list.image.url), list
			.panel.body
				%h2= link_to list.title, list
				%p.user
				Por 
				= list.user.username

app/views/lists/new.html.haml
- content_for :title, "Criar Lista"
.col-md-6.col-md-offset-3
	.row
		.panel.panel-default
			.panel-heading
				%h1 New Form
			.panel-body
				= render 'form'
				%br/
				= link_to "Back", root_path

app/views/lists/show.html.haml
- content_for :title, @list.tag_list.first + "(por " + @list.user.username + ")"
#list_show.row
	.col-md-8.col-md-offset-2
		.panel.panel-default
			- if @list.image.present?
				.panel-heading.list_image
					= image_tag @list.image.url
			.panel-body
				- @list.tags.any?
				%h1= @list.tag_list.first
				%h3= "(por " + @list.user.username + ")"
				%p= @list.description
				%ol
					- for listitem in @list.list_items
						%li= listitem.title
						%br/
			.panel-footer
				.row
					.col-md-6
						%p.user
						Submitted by 
						= @list.user.username
					.col-md-6
						.btn-group.pull-right
							= link_to like_list_path(@list), method: :put, class: "btn btn-default" do
								%span.glyphicon.glyphicon-heart
									= @list.get_upvotes.size
							- if user_signed_in?
								= link_to "Edit", edit_list_path, class: "btn btn-default"
								= link_to "Delete", list_path, method: :delete, data:  { confirm: "Are you sure?" }, class: "btn btn-default"

app/views/tag/show.html.haml
- content_for :title, @tag.name
%h1= @tag.name
#lists.transitions-enabled
	- @lists.each do |list|
		.box.panel.panel-default
			- if list.image.present?
				= link_to (image_tag list.image.url), list
			.panel.body
				%h2= link_to list.title, list
				%p.user
				Por  
				= list.user.email